In [1]:
import geopandas as gpd

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geopandas/_compat.py:123: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.4-CAPI-1.16.2). Conversions between both will be slow.
  warnings.warn(

In [3]:
# Read File====
# Download from https://github.com/microsoft/USBuildingFootprints
bld = gpd.read_file("/Volumes/volume 1/GIS Projects/nightlight/phoenix/building_footprint/Arizona.geojson")

In [7]:
boundary = gpd.read_file("/Users/naoyamorishita/Documents/working/nightlight/data/grid.geojson")
boundary = boundary.to_crs(bld.crs)

In [8]:
bld.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [9]:
boundary.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [10]:
bld_phoenix = bld.clip(boundary)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/geopandas/tools/clip.py:67: FutureWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  clipped.loc[

In [11]:
bld_phoenix

,release,capture_dates_range,geometry
511030,2,5/7/2020-5/21/2020,"POLYGON ((-111.94548 33.44751, -111.94572 33.4..."
334186,2,5/7/2020-5/21/2020,"POLYGON ((-111.94431 33.44760, -111.94440 33.4..."
2534307,2,5/7/2020-5/21/2020,"POLYGON ((-111.94640 33.44758, -111.94640 33.4..."
841791,2,5/7/2020-5/21/2020,"POLYGON ((-111.94901 33.44710, -111.94914 33.4..."
1829169,2,5/7/2020-5/21/2020,"POLYGON ((-111.94870 33.44740, -111.94856 33.4..."
...,...,...,...
366986,2,5/22/2020-5/27/2020,"POLYGON ((-112.19049 33.73869, -112.19055 33.7..."
1442930,2,5/22/2020-5/27/2020,"POLYGON ((-112.18977 33.73863, -112.18985 33.7..."
73943,2,5/22/2020-5/27/2020,"POLYGON ((-112.19005 33.73874, -112.19003 33.7..."
1255043,2,5/22/2020-5/27/2020,"POLYGON ((-112.19049 33.73909, -112.19040 33.7..."
720305,2,5/22/2020-5/27/2020,"POLYGON ((-112.19077 33.73913, -112.19072 33.7..."

In [13]:
ph = gpd.read_file("/Users/naoyamorishita/Documents/working/nightlight/data/ph_phoenix.geojson")

In [22]:
bld_phoenix = bld_phoenix.to_crs(26949)

In [27]:
bld_phoenix.crs

<Derived Projected CRS: EPSG:26949>
Name: NAD83 / Arizona Central
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: United States (USA) - Arizona - counties Coconino; Maricopa; Pima; Pinal; Santa Cruz; Yavapai.
- bounds: (-113.35, 31.33, -110.44, 37.01)
Coordinate Operation:
- name: SPCS83 Arizona Central zone (meters)
- method: Transverse Mercator
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [30]:
bld_phoenix["sqm"] = bld_phoenix.area
bld_phoenix

,release,capture_dates_range,geometry,sqm
511030,2,5/7/2020-5/21/2020,"POLYGON ((210681.152 271379.479, 210658.932 27...",258.203747
334186,2,5/7/2020-5/21/2020,"POLYGON ((210790.393 271389.652, 210781.933 27...",107.021999
2534307,2,5/7/2020-5/21/2020,"POLYGON ((210596.087 271387.488, 210595.628 27...",410.565401
841791,2,5/7/2020-5/21/2020,"POLYGON ((210352.770 271334.549, 210340.963 27...",1275.012563
1829169,2,5/7/2020-5/21/2020,"POLYGON ((210381.973 271367.034, 210394.621 27...",228.999877
...,...,...,...,...
366986,2,5/22/2020-5/27/2020,"POLYGON ((187988.378 303706.130, 187982.545 30...",260.811928
1442930,2,5/22/2020-5/27/2020,"POLYGON ((188054.704 303699.189, 188047.854 30...",321.566312
73943,2,5/22/2020-5/27/2020,"POLYGON ((188028.791 303711.235, 188030.655 30...",243.845215
1255043,2,5/22/2020-5/27/2020,"POLYGON ((187988.217 303750.161, 187996.811 30...",257.440458
720305,2,5/22/2020-5/27/2020,"POLYGON ((187962.749 303754.887, 187967.006 30...",27.705271

In [31]:
ph = ph.to_crs(26949)
ph.crs

<Derived Projected CRS: EPSG:26949>
Name: NAD83 / Arizona Central
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: United States (USA) - Arizona - counties Coconino; Maricopa; Pima; Pinal; Santa Cruz; Yavapai.
- bounds: (-113.35, 31.33, -110.44, 37.01)
Coordinate Operation:
- name: SPCS83 Arizona Central zone (meters)
- method: Transverse Mercator
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [32]:
phbld = ph.sjoin_nearest(bld_phoenix)

In [34]:
phbld
plot

,OBJECTID,TOTAL_OCCUPIED,OBJECTID.1,NAME,geometry,index_right,release,capture_dates_range,sqm
0,259,0,2563,City of Phoenix,POINT (197305.535 270371.480),2562307,2,5/7/2020-5/21/2020,289.445845
1,315,2,2563,City of Phoenix,POINT (197653.497 270448.429),2315012,2,5/7/2020-5/21/2020,148.985329
75,24835,0,2563,City of Phoenix,POINT (197647.918 270448.438),2315012,2,5/7/2020-5/21/2020,148.985329
136,46081,0,2563,City of Phoenix,POINT (197659.168 270448.420),2315012,2,5/7/2020-5/21/2020,148.985329
2,317,1,2563,City of Phoenix,POINT (197480.929 270448.711),1636721,2,5/7/2020-5/21/2020,206.466495
...,...,...,...,...,...,...,...,...,...
570,194093,1,2563,City of Phoenix,POINT (193300.968 282872.182),69690,2,5/15/2020-5/22/2020,391.289420
572,194329,1,2563,City of Phoenix,POINT (193230.965 294085.702),549214,2,4/1/2018-6/1/2018,173.468113
574,194941,1,2563,City of Phoenix,POINT (201000.728 275243.072),347980,2,5/7/2020-5/21/2020,147.577390
575,195104,0,2563,City of Phoenix,POINT (206161.111 289823.174),520712,2,5/15/2020-5/22/2020,190.244473
576,196394,1,2563,City of Phoenix,POINT (193079.048 283892.188),1743426,2,5/15/2020-5/22/2020,239.990539

In [35]:
phbld.to_file("/Users/naoyamorishita/Documents/working/nightlight/data/bldph_new.geojson")